openapi: 3.0.1
info:
  title: '@cantire-corp/cds.notifications-sender-api'
  version: 0.1.11
  description: Notification Sender API
  license:
    name: ISC
  contact:
    name: CDS Team
servers:
  - url: /notification
paths:
  /health:
    get:
      tags:
        - health
      summary: Service health
      description: Service health
      operationId: get-health
      responses:
        '200':
          description: An Health object
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/HealthGet200ApplicationJsonResponse'
              example:
                build: string
                message: string
                status: string
                uptime: 0
  /send:
    post:
      tags:
        - Notification
      summary: Sends notification with specified provider
      description: Sends notification with specified provider
      operationId: post-send
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/SendPostRequest'
            example:
              storeNumber: '0100'
              template: Chit_Order_cancelled_customer
              communicationType: SMS
              provider: Twilio
              language: fr
              destinationPhone:
                - '6135550113'
              destinationEmail: []
              templateContent:
                - name: ORDER_NUMBER
                  value: this-is-order-number
      responses:
        '200':
          description: Notification was successfully sent
        '400':
          description: Request parameters validation error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/SendPost400ApplicationJsonResponse'
              example:
                errorCode: 400
                errorMessage: No Valid Provider Account
                errorDetails:
                  - Please configure Store 0100 for this service or allow service through Global Account
                template: ShareCart
                communicationType: SMS
                provider: Twilio
        '500':
          description: Internal server error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/SendPost500ApplicationJsonResponse'
              example:
                status: failed
                message: System Error.
  /execute-flow:
    post:
      tags:
        - Notification
      summary: Executes flow with specified provider by template name
      description: Executes flow with specified provider by template name
      operationId: post-execute-flow
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/Execute-flowPostRequest'
            example:
              storeNumber: '0100'
              template: ShareCart
              communicationType: SMS
              language: fr
              provider: Twillio
              from: 647XXXXXXX
              destinationPhone: []
              destinationEmail: []
              templateContent:
                - name: name
                  value: test
                - name: sc_url
                  value: test
      responses:
        '200':
          description: Execution created
        '400':
          description: Request parameters validation error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Execute-flowPost400ApplicationJsonResponse'
              example:
                errorCode: 200
                errorMessage: Failed to execute flow. The requested resource /Flows/FW53d093d51446b9bf88a40f6b255d2a40/Executions was not found
                errorDetails:
                  - 380-681-2345
                  - 380-681-2345
                template: ShareCart
                provider: Twilio
        '500':
          description: Internal server error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Execute-flowPost500ApplicationJsonResponse'
              example:
                status: failed
                message: System Error.
components:
  schemas:
    HealthGet200ApplicationJsonResponse:
      type: object
      properties:
        build:
          type: string
        message:
          type: string
        status:
          type: string
        uptime:
          type: number
    SendPostRequest:
      required:
        - communicationType
        - language
        - provider
        - storeNumber
        - template
        - templateContent
      type: object
      properties:
        storeNumber:
          type: string
        template:
          type: string
        communicationType:
          type: string
        provider:
          type: string
        language:
          type: string
        destinationEmail:
          type: array
          items:
            type: string
        destinationPhone:
          type: array
          items:
            type: string
        templateContent:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
    SendPost400ApplicationJsonResponse:
      required:
        - errorCode
        - errorDetails
        - errorMessage
      type: object
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
        errorDetails:
          type: array
          items:
            type: string
        template:
          type: string
        communicationType:
          type: string
        provider:
          type: string
      example:
        errorCode: 400
        errorMessage: No Valid Provider Account
        errorDetails:
          - Please configure Store 0100 for this service or allow service through Global Account
        template: ShareCart
        communicationType: SMS
        provider: Twilio
    SendPost500ApplicationJsonResponse:
      required:
        - message
        - status
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      example:
        status: failed
        message: System Error.
    Execute-flowPostRequest:
      required:
        - communicationType
        - language
        - provider
        - storeNumber
        - template
        - templateContent
      type: object
      properties:
        storeNumber:
          type: string
        template:
          type: string
        communicationType:
          type: string
        provider:
          type: string
        language:
          type: string
        destinationEmail:
          type: array
          items:
            type: string
        destinationPhone:
          type: array
          items:
            type: string
        templateContent:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
    Execute-flowPost400ApplicationJsonResponse:
      required:
        - errorCode
        - errorDetails
        - errorMessage
      type: object
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
        errorDetails:
          type: string
        template:
          type: string
        communicationType:
          type: string
        provider:
          type: string
      example:
        errorCode: 200
        errorMessage: Failed to execute flow. The requested resource /Flows/FW53d093d51446b9bf88a40f6b255d2a40/Executions was not found
        errorDetails:
          - 380-681-2345
          - 380-681-2345
        template: ShareCart
        provider: Twilio
    Execute-flowPost500ApplicationJsonResponse:
      required:
        - message
        - status
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      example:
        status: failed
        message: System Error.
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []